---
- name: Add repository
  become: true
  deb822_repository:
    name: insync
    types: deb
    uris: http://apt.insync.io/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components:
      - non-free
      - contrib
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xAEEB94E9C5A3B54ECFA4A66AA684470CACCAF35C
    state: present

- name: Install
  become: true
  apt:
    update_cache: yes
    name: insync
