---
- name: Import GPG key
  become: true
  shell: |
    gpg --no-default-keyring --keyring /usr/share/keyrings/insync-archive-keyring.gpg --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C
  args:
    creates: /usr/share/keyrings/insync-archive-keyring.gpg

- name: Add repository
  become: true
  deb822_repository:
    name: insync
    types: deb
    uris: http://apt.insync.io/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components:
      - non-free
      - contrib
    signed_by: /usr/share/keyrings/insync-archive-keyring.gpg
    state: present
  register: insync_repo

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  when: insync_repo.changed

- name: Install
  become: true
  apt:
    name: insync
