---
- name: Add apt key
  become: true
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: C5AD17C747E3415A3642D57D77C6C491D6AC1D69
    state: present

- name: Add repository
  become: true
  apt_repository:
    repo: deb https://dl.k6.io/deb stable main
    state: present
  register: k6_repo

- name: Update apt cache if repo was added
  become: true
  apt: update_cache=yes
  when: k6_repo.changed

- name: Install
  become: true
  apt:
    name: k6
    state: present
