---
- name: Import GPG key
  become: true
  shell: |
    gpg -k
    gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
  args:
    creates: /usr/share/keyrings/k6-archive-keyring.gpg

- name: Add repository
  become: true
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main
  register: k6_repo

- name: Install
  become: true
  apt:
    name: k6
