---
- name: Import GPG key
  become: true
  shell: |
    gpg -k
    gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
  args:
    creates: /usr/share/keyrings/k6-archive-keyring.gpg

- name: Add repository
  become: true
  deb822_repository:
    name: k6
    types: deb
    uris: https://dl.k6.io/deb
    suites: stable
    components: main
    signed_by: /usr/share/keyrings/k6-archive-keyring.gpg
    state: present
  register: k6_repo

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  when: k6_repo.changed

- name: Install
  become: true
  apt:
    name: k6
