---
- name: Check for existing binary
  stat:
    path: ~/.pulumi/bin
  register: pulumi_install
  changed_when: False

- block:
    - name: Install
      shell: curl -fsSL https://get.pulumi.com | sh

    - name: Ensure OMZ completion directory exists
      file:
        path: ~/.oh-my-zsh/completions
        state: directory

    - name: Install auto complete
      shell: ~/.pulumi/bin/pulumi gen-completion zsh > ~/.oh-my-zsh/completions/_pulumi
  when: not pulumi_install.stat.exists or force_install is true

- name: Add bin to PATH
  become: true
  copy:
    dest: /etc/profile.d/pulumi.sh
    mode: 0644
    content: export PATH="${PATH}:/home/{{ ansible_user_id }}/.pulumi/bin"
