---
- name: Check for existing binary
  stat:
    path: ~/.pulumi/bin
  register: pulumi_install
  changed_when: False

- block:
    - name: Install
      shell: curl -fsSL https://get.pulumi.com | sh -s -- --version=3.22.0
  when: not pulumi_install.stat.exists

- name: Add bin to PATH
  become: true
  copy:
    dest: /etc/profile.d/pulumi.sh
    mode: 0644
    content: export PATH="${PATH}:/home/{{ ansible_user }}/.pulumi/bin"
