# Install doc: https://developers.yubico.com/yubioath-desktop/
---
- import_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Install ykman
  pip:
    name: 'yubikey-manager==4.*'
    state: present
    extra_args: --user

- name: Check for existing install
  stat:
    path: ~/AppImages/yubioath-desktop-latest-linux.AppImage
  register: yubioath_install
  changed_when: False

- block:
    - name: Create AppImages directory
      file:
        path: ~/AppImages/
        state: directory
        mode: 0755

    - name: Install yubioath logo
      become: true
      copy:
        src: com.yubico.yubioath.svg
        dest: /usr/share/pixmaps/com.yubico.yubioath.svg

    - name: Install authenticator
      get_url:
        url: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-latest-linux.AppImage
        dest: ~/AppImages/yubioath-desktop-latest-linux.AppImage
        mode: 0755
  when: not yubioath_install.stat.exists

- name: Install .desktop
  copy:
    dest: ~/.local/share/applications/com.yubico.yubioath.desktop
    content: |
      [Desktop Entry]
      Name=Yubico Authenticator
      GenericName=Yubico Authenticator
      Comment=Graphical interface for displaying OATH codes with a YubiKey.
      Exec=/home/{{ ansible_user }}/AppImages/yubioath-desktop-latest-linux.AppImage
      Icon=com.yubico.yubioath
      StartupNotify=false
      StartupWMClass=yubioath-desktop
      Terminal=false
      Type=Application
      Categories=Utility;
      Keywords=Yubico;Authenticator;
  register: yubioath_file

- name: Update desktop files
  command: update-desktop-database ~/.local/share/applications -v
  when: yubioath_file.changed
