---
- name: Install Yubico repository
  become: true
  apt_repository:
    repo: ppa:yubico/stable

- name: Install Yubico
  apt:
    name:
      - libpam-u2f
      - yubioath-desktop
      - yubikey-manager
