---
- name: Install requirements
  become: true
  apt:
    name:
      - swig
      - libpcsclite1
      - libpcsclite-dev
      - pcscd
      - pcsc-tools
#      - opensc
#      - opensc-pkcs11
      - yubico-piv-tool
      - libpam-sss
      - yubikey-manager
      - yubikey-manager-qt

# See: https://github.com/ansible/ansible/issues/22303
- name: Configure pcscd socket
  become: true
  service:
    name: pcscd.socket
    state: started
    enabled: true

- name: Configure pcscd service
  become: true
  service:
    name: pcscd.service
    state: started
    enabled: true
