---
- name: Install requirements
  become: true
  apt:
    name:
      - swig
      - libpcsclite1
      - libpcsclite-dev
      - pcscd
      - pcsc-tools
      - opensc
      - opensc-pkcs11
      - yubico-piv-tool
      - libpam-sss

# See: https://github.com/ansible/ansible/issues/22303
- name: Ensure pcscd service is running
  become: true
  service:
    name: pcscd
    state: started
    enabled: true
