---
- import_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Install pip packages
  pip:
    name: '{{ packages }}'
    state: present
    extra_args: --user
  vars:
    packages:
      - s-tui
      - psutil
      - youtube-dl
      - jmespath
