---
- import_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Install pip packages
  community.general.pipx:
    name: '{{ item }}'
  with_items:
    - s-tui
    - youtube-dl
    - git+https://github.com/micoli/fixup-chooser.git
