---
- name: Install packages
  become: true
  apt:
    state: present
    name:
      - apt-file
      - lnav
      - stress
      - meld
      - bash-completion
      - screenfetch
      - htop
      - nmon
      - hdparm
      - xclip
      - smartmontools
      - sysbench
      - iotop
      - fio
      - multitail
      - git
      - git-extras
      - ssh
      - vim
      - vim-gui-common
      - zsh
      - tar
      - fonts-hack
      - unzip
      - netstat-nat
      - net-tools
      - tmux
      - openvpn
      - openssl
      - network-manager-openvpn-gnome
      - resolvconf
      - tzdata
      - locales
      - shellcheck
      - gnome-tweaks
      - gnome-shell-extensions
      - gnome-characters
      - gnome-sound-recorder
      - menulibre
      - apt-transport-https
      - ca-certificates
      - curl
      - gir1.2-gst-plugins-base-1.0 # gstreamer for nothing-to-say plugin
      - imagemagick
      - gthumb
      - nautilus-image-converter
      - keychain
      - postfix
      - mailutils
      - ncdu
      - pandoc
      - libnss3-tools
      - pdftk
      - inkscape
      - gnupg2
      - entr
      - gdebi
      - fonts-roboto
      - wondershaper
      - chrome-gnome-shell
      - flameshot
      - jq
      - vlc
      - fd-find # find like: https://github.com/sharkdp/fd
      - bat # find like: https://github.com/sharkdp/bat
      - hyperfine # benchmarking: https://github.com/sharkdp/hyperfine
      - fzf # cli fuzzy search and more: https://github.com/junegunn/fzf
      - ripgrep # grep like: https://github.com/BurntSushi/ripgrep
      - exa # ls like: https://github.com/ogham/exa
      - httpie
      - visidata
      - libnotify-bin
      - nfs-common
      #- openjdk-11-jre-headless
      #- klavaro # Typing tool

- name: fd symlink
  become: true
  file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link

- name: bat symlink
  become: true
  file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
