---
- name: Install packages
  become: true
  apt:
    state: present
    name:
      - apt-file
      - lnav
      - stress
      - meld
      - bash-completion
      - screenfetch
      - htop
      - nmon
      - hdparm
      - xclip
      - smartmontools
      - sysbench
      - iotop
      - fio
      - multitail
      - git
      - git-extras
      - ssh
      - vim
      - vim-gui-common
      - zsh
      - tar
      - fonts-hack
      - unzip
      - netstat-nat
      - net-tools
      - powerline
      - tmux
      - openvpn
      - openssl
      - network-manager-openvpn-gnome
      - resolvconf
      - tzdata
      - locales
      - shellcheck
      - gnome-tweaks
      - gnome-shell-extensions
      - menulibre
      - apt-transport-https
      - ca-certificates
      - curl
      - imagemagick
      - gthumb
      - nautilus-image-converter
      - keychain
      - postfix
      - mailutils
      - ncdu
      - pandoc
      - libnss3-tools
      - gnupg2
      - entr
      - gdebi
      - fonts-roboto
      - wondershaper
      - chrome-gnome-shell
      - flameshot
      - jq
      - vlc
      - fd-find # find like: https://github.com/sharkdp/fd
      - bat # find like: https://github.com/sharkdp/bat
      - hyperfine # benchmarking: https://github.com/sharkdp/hyperfine
      - fzf # cli fuzzy search and more: https://github.com/junegunn/fzf
