---
- name: Main playbook to setup machine
  hosts: localhost
  gather_facts: yes
  gather_subset: [ min ]
  vars:
    ansible_user: benoit
    jetbrains_toolbox_version: latest
    force_install: false
  vars_files:
    - vault.yaml
  pre_tasks:
    - name: Debug info
      debug:
        msg: |
          OS Family: {{ ansible_os_family }}
          Distribution: {{ ansible_distribution }}
          Distribution release: {{ ansible_distribution_release }}
          Distribution version: {{ ansible_distribution_version }}
          Distribution major version: {{ ansible_distribution_major_version }}
  roles:
    - user
    - system
    - gnome-settings
    - fonts
    - dotfiles
    - git-delta
    - z
    - software
    - jaredhocutt.jetbrains_toolbox
    - firefox-dev
    - bitwarden
    - rust
    - alacritty
    - php
    - nodejs
    - phpstorm-url-handler
    - docker
    - awscli
    #- dbeaver
    - keepassxc
    #- peek
    - vscode
    - yubico
    - spotify
    - unipdf-cli
    - pdfcpu
    - stellar
    - slack
    - mkcert
    - croncape
    - hexyl
    - discord
    - keybase
    #- gitlab-runner
    #- drawio
    - pulumi
    - auth0
    - k6
    - grex # It generates regular expressions from examples
    - bandwhich # Terminal bandwidth utilization tool
    - stoplight-studio
    - chrome
    - obsidian
    - github-cli
    - dstp
    - postman
    - litra
    - task
    - trdsql
    - helm
