---
- name: Main playbook to setup machine
  hosts: localhost
  gather_facts: yes
  gather_subset: [ min ]
  vars:
    jetbrains_toolbox_version: latest
    force_install: false
  pre_tasks:
    - name: Debug info
      debug:
        msg: |
          Ansible env home: {{ ansible_env.HOME }}
          Ansible user id: {{ ansible_user_id }}
          OS Family: {{ ansible_os_family }}
          Distribution: {{ ansible_distribution }}
          Distribution release: {{ ansible_distribution_release }}
          Distribution version: {{ ansible_distribution_version }}
          Distribution major version: {{ ansible_distribution_major_version }}
  roles:
    - user
    - system
    - software
    - fonts
    - gnome-settings
    - dotfiles
    - bitwarden
    - yubico
    - slack
    - alacritty
    - zellij
    - z
    - firefox-dev
    - git-delta
    - jaredhocutt.jetbrains_toolbox
    - phpstorm-url-handler
    - discord
    - keybase
    - rust
    - php
    - nvm
    #- nodejs
    - docker
    - awscli
    #- peek
    #- vscode
    - mkcert
    - croncape
    - hexyl
    - unipdf-cli
    - pdfcpu
    - obsidian
    - github-cli
    - dstp
    - postman
    - task
    - helm
    - trdsql
    - bandwhich # Terminal bandwidth utilization tool
    - chrome
    - spotify
    - pulumi
    - auth0
    - k6
    - litra
    - stoplight-studio
