---
- import_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Set ZSH shell for {{ ansible_user_id }}
  become: true
  user: name={{ ansible_user_id }} shell=/bin/zsh state=present

- name: Config user {{ ansible_user_id }}
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: adm,mail,users
    append: yes
    createhome: no
  when: ansible_os_family == 'Debian'

- name: Config user {{ ansible_user_id }}
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: wheel,adm,users,mail
    append: yes
    createhome: no
  when: ansible_os_family == 'RedHat'

- name: User config ~/.config/environment.d/user.conf
  copy:
    content: |
      PATH="$PATH:{{ ansible_env.HOME }}/.local/bin"
      BAT_THEME="Monokai Extended Light"
    dest: ~/.config/environment.d/user.conf
    mode: 0644
