---
- import_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Set ZSH shell for {{ ansible_user }}
  become: true
  user: name={{ ansible_user }} shell=/bin/zsh state=present

- name: Add some groups to user {{ ansible_user }}
  become: true
  user:
    name: '{{ ansible_user }}'
    groups: wheel,adm,users,mail
    append: yes
  when: ansible_os_family == 'RedHat'
