---
- name: Ensure apt-transport-https is installed.
  become: true
  apt: name=apt-transport-https state=present

- name: Add Nodesource apt key.
  become: true
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: nodejs
    update_cache: false
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
  register: node_repo

- name: 'Update apt cache if repo was added.'
  become: true
  apt: update_cache=yes
  when: node_repo.changed

- name: 'Ensure Node.js and npm are installed.'
  become: true
  apt: "name=nodejs={{ nodejs_version }}* state=present"
