---
- name: Install packages
  become: true
  apt:
    state: present
    name:
      - gnome-tweaks
      - gnome-shell-extensions
      - gnome-shell-extension-manager

- name: Install pip packages
  community.general.pipx:
    name: '{{ item }}'
  with_items:
    - gnome-extensions-cli

- name: Install Gnome extensions
  shell: |
    set -x
    # Turn off some extensions
    gnome-extensions disable tiling-assistant@ubuntu.com
    
    # Install new extensions
    gext install tilingshell@ferrarodomenico.com
    
    # Compile gsettings schemas in order to be able to set them
    sudo cp ~/.local/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com/schemas/org.gnome.shell.extensions.tilingshell.gschema.xml /usr/share/glib-2.0/schemas/
    sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

# To find some settings:
#  -  gsettings list-recursively | grep -i <KEYWORD>
#  -  dconf dump / | grep -i <KEYWORD>
#  -  dconf watch <KEY>
- name: Apply gnome config for Pop!_OS
  shell: |
    set -x
    
    # Tiling
    gsettings set org.gnome.shell.extensions.pop-shell active-hint true
    gsettings set org.gnome.shell.extensions.pop-shell gap-inner 'uint32 1'
    gsettings set org.gnome.shell.extensions.pop-shell gap-outer 'uint32 1'
    gsettings set org.gnome.shell.extensions.pop-shell hint-color-rgba 'rgba(251,184,108,0.797297)'
    gsettings set org.gnome.shell.extensions.pop-shell tile-by-default true
  when: ansible_distribution == 'Pop!_OS'

- name: Apply gnome config
  shell: |
    set -x

    # Tiling Shell
    gsettings set org.gnome.shell.extensions.tilingshell layouts-json '[{"id":"Layout 1","tiles":[{"x":0,"y":0,"width":0.22,"height":0.5,"groups":[1,2]},{"x":0,"y":0.5,"width":0.22,"height":0.5,"groups":[1,2]},{"x":0.22,"y":0,"width":0.56,"height":1,"groups":[2,3]},{"x":0.78,"y":0,"width":0.22,"height":0.5,"groups":[3,4]},{"x":0.78,"y":0.5,"width":0.22,"height":0.5,"groups":[3,4]}]},{"id":"Layout 2","tiles":[{"x":0,"y":0,"width":0.22,"height":1,"groups":[1]},{"x":0.22,"y":0,"width":0.56,"height":1,"groups":[1,2]},{"x":0.78,"y":0,"width":0.22,"height":1,"groups":[2]}]},{"id":"Layout 3","tiles":[{"x":0,"y":0,"width":0.33,"height":1,"groups":[1]},{"x":0.33,"y":0,"width":0.67,"height":1,"groups":[1]}]},{"id":"Layout 4","tiles":[{"x":0,"y":0,"width":0.67,"height":1,"groups":[1]},{"x":0.67,"y":0,"width":0.33,"height":1,"groups":[1]}]},{"id":"30678093","tiles":[{"x":0,"y":0,"width":0.5,"height":1,"groups":[1]},{"x":0.5,"y":0,"width":0.49999999999999994,"height":1,"groups":[1]}]}]'
    gsettings set org.gnome.shell.extensions.tilingshell inner-gaps 4
    gsettings set org.gnome.shell.extensions.tilingshell outer-gaps 4

    # Appearance
    gsettings set org.gnome.desktop.interface enable-animations true
    gsettings set org.gnome.desktop.interface font-hinting 'none'
    gsettings set org.gnome.desktop.interface monospace-font-name "JetBrainsMono Nerd Font Mono 12"

    # Reveal week numbers in the Gnome calendar
    gsettings set org.gnome.desktop.calendar show-weekdate true

    # Dock
    gsettings set org.gnome.shell.extensions.dash-to-dock intellihide true
    gsettings set org.gnome.shell.extensions.dash-to-dock intellihide-mode 'ALL_WINDOWS'
    gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
    gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
    gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
    gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false

    # Workspace
    gsettings set org.gnome.mutter workspaces-only-on-primary true

    # Reset shortcut for screenshot
    gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot []
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    gsettings set org.gnome.shell.keybindings show-screenshot-ui []

    # Use Flameshot for screenshot and bind shortcut see https://askubuntu.com/questions/1036473/ubuntu-18-how-to-change-screenshot-application-to-flameshot
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Flameshot'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'sh -c -- "flameshot gui"' 
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding 'Print'

    # Set shortcut to mute mic
    gsettings set org.gnome.settings-daemon.plugins.media-keys email-static []
    gsettings set org.gnome.settings-daemon.plugins.media-keys mic-mute '["Pause", "Mail", "<Ctrl>Mail"]'

    # Set shortcut to switch windows
    gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Shift><Alt>Tab']"
    gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
    gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super>Tab']"
    gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Super>Tab']"

    # General settings
    gsettings set org.gnome.desktop.privacy report-technical-problems false
    gsettings set org.gnome.system.location enabled false
    gsettings set org.gnome.desktop.interface clock-format '24h'
    gsettings set org.gnome.system.locale region 'fr_FR.UTF-8'
    gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'nothing'
    gsettings set org.gnome.GWeather temperature-unit 'centigrade'

    # Numlock
    gsettings set org.gnome.desktop.peripherals.keyboard numlock-state true
    gsettings set org.gnome.desktop.peripherals.keyboard remember-numlock-state true

    # Lock behaviors
    gsettings set org.gnome.desktop.session idle-delay 300
    gsettings set org.gnome.desktop.screensaver lock-delay 0
    gsettings set org.gnome.desktop.screensaver lock-enabled false

    # Night mode display
    gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic false
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from 0.0
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to 23.99
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 'uint32 3200'
