---
- name: Add NetBird GPG key to keyring
  become: true
  shell: |
    curl -sSL https://pkgs.netbird.io/debian/public.key | gpg --dearmor --output /usr/share/keyrings/netbird-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/netbird-archive-keyring.gpg

- name: Add NetBird APT repository
  become: true
  deb822_repository:
    name: netbird
    types: deb
    uris: https://pkgs.netbird.io/debian
    suites: stable
    components: main
    signed_by: /usr/share/keyrings/netbird-archive-keyring.gpg
    state: present
  notify: Update apt cache

- meta: flush_handlers

- name: Install NetBird
  become: true
  apt:
    name: [netbird, netbird-ui]
    state: present
