---
- name: Add NetBird GPG key to keyring
  become: true
  shell: |
    wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null
  args:
    creates: /etc/apt/keyrings/mise-archive-keyring.gpg

- name: Add APT repository
  become: true
  deb822_repository:
    name: mise
    types: deb
    uris: https://mise.jdx.dev/deb
    suites: stable
    components: main
    architectures: amd64
    signed_by: /etc/apt/keyrings/mise-archive-keyring.gpg
    state: present
  notify: Update apt cache

- meta: flush_handlers

- name: Install
  become: true
  apt:
    name: [mise]
    state: present
