---
# Source: https://derickrethans.nl/luminous-logitech-litra-on-linux.html
# Driver: https://github.com/kharyam/litra-driver

- name: Udev rule
  become: true
  copy:
    dest: /etc/udev/rules.d/82-litra-glow.rules
    content: |
      SUBSYSTEM=="usb", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c900", MODE:="0666", GROUP="plugdev"
  register: phpstorm_url_handler_desktop_file
  notify: update udev rules

- meta: flush_handlers

- name: Install driver
  community.general.pipx:
    name: litra-driver

- name: Install dependencies
  become: true
  apt:
    name:
      - python3-tk
      - gir1.2-appindicator3-0.1
    state: present

- name: Install .desktop
  copy:
    dest: ~/.local/share/applications/litra-lcui.desktop
    content: |
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Litra Glow UI
      Comment=Litra driver from https://github.com/kharyam/litra-driver
      Icon=sunny
      Categories=Utility;
      Exec=lcui
      Terminal=false
  register: litra_desktop_file

- name: Update desktop files
  command: update-desktop-database ~/.local/share/applications -v
  when: litra_desktop_file.changed
