---
- name: Add GPG key to keyring
  become: true
  shell: |
    curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | gpg --dearmor --yes -o /usr/share/keyrings/spotify.gpg
  args:
    creates: /usr/share/keyrings/spotify.gpg

- name: Add APT repository
  become: true
  deb822_repository:
    name: spotify
    types: deb
    uris: https://repository.spotify.com
    suites: stable
    components: non-free
    signed_by: /usr/share/keyrings/spotify.gpg
    state: present
  notify: Update apt cache

- meta: flush_handlers

- name: Install
  become: true
  apt:
    name: [spotify-client]
