---
- name: Check for existing slack install
  command: dpkg-query -W slack-desktop
  register: slack_installed
  failed_when: false
  changed_when: false

- block:
    - name: Download and install
      become: true
      apt:
        deb: https://downloads.slack-edge.com/releases/linux/4.26.1/prod/x64/slack-desktop-4.26.1-amd64.deb
  when: slack_installed.rc == 1
