---
- name: Add GPG key to keyring
  become: true
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor --yes -o /etc/apt/keyrings/google-chrome.gpg
  args:
    creates: /etc/apt/keyrings/google-chrome.gpg

- name: Add apt repository
  become: true
  deb822_repository:
    name: google-chrome
    types: deb
    uris: https://dl.google.com/linux/chrome/deb/
    suites: stable
    components: main
    architectures: amd64
    signed_by: /etc/apt/keyrings/google-chrome.gpg
    state: present

- name: Install
  become: true
  apt:
    name: google-chrome-stable
