---
- name: Import GPG key
  become: true
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: 0644

- name: Add GitHub CLI repository
  become: true
  deb822_repository:
    name: github-cli
    types: deb
    uris: https://cli.github.com/packages
    suites: stable
    components: main
    architectures: amd64
    signed_by: /usr/share/keyrings/githubcli-archive-keyring.gpg
    state: present

- name: Install GitHub CLI
  become: true
  apt:
    update_cache: yes
    name: gh
