---
- import_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Ensure docker users are added to the docker group.
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Add docker config with environment variables
  become: true
  copy:
    dest: /etc/profile.d/docker.sh
    mode: 0644
    content: |
      export DOCKER_BUILDKIT=1

- name: ensure docker is running
  become: true
  service:
    name: docker
    enabled: yes
    state: started

#- import_tasks: docker-compose.yaml

- meta: flush_handlers
