---
- name: Check for existing GPG key
  become: true
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg
  changed_when: False

- name: Import GPG key
  become: true
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: not docker_gpg.stat.exists

- name: Add Docker repository.
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: install docker
  become: true
  apt:
    name: '{{ packages }}'
  vars:
    packages:
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
