---
- name: Check for existing Symfony CLI install
  command: /usr/local/bin/symfony version
  register: symfony_cli_install
  changed_when: symfony_cli_version not in symfony_cli_installed_version.stdout | default('')
  failed_when: False

- block:
    - name: Download
      get_url:
        url: https://github.com/symfony-cli/symfony-cli/releases/download/v{{ symfony_cli_version }}/symfony-cli_linux_amd64.tar.gz
        dest: /tmp/symfony.tar.gz
        mode: 0755
        force: yes
        checksum: "sha256:https://github.com/symfony-cli/symfony-cli/releases/download/v{{ symfony_cli_version }}/checksums.txt"

    - name: Install
      become: true
      unarchive:
        src: /tmp/symfony.tar.gz
        dest: /usr/local/bin
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        extra_opts: [--wildcards, symfony]
        remote_src: yes

    - name: Check
      command: /usr/local/bin/symfony version
  when: symfony_cli_version not in symfony_cli_installed_version.stdout | default('')
