---
- name: Symfony CLI | Get the latest release from GitHub API
  uri:
    url: "https://api.github.com/repos/symfony-cli/symfony-cli/releases/latest"
    return_content: yes
  register: response
  no_log: true

- name: Symfony CLI | Get version number
  set_fact:
    symfony_cli_version: "{{ response.json | json_query('name') | regex_replace('^.', '') }}"

- name: Symfony CLI | Check for existing install
  command: /usr/local/bin/symfony version
  register: symfony_cli_installed_version
  changed_when: symfony_cli_version not in symfony_cli_installed_version.stdout | default('')
  failed_when: False

- block:
    - name: Symfony CLI | Download
      get_url:
        url: https://github.com/symfony-cli/symfony-cli/releases/download/v{{ symfony_cli_version }}/symfony-cli_linux_amd64.tar.gz
        dest: /tmp/symfony.tar.gz
        mode: 0755
        force: yes
        checksum: "sha256:https://github.com/symfony-cli/symfony-cli/releases/download/v{{ symfony_cli_version }}/checksums.txt"

    - name: Symfony CLI | Install
      become: true
      unarchive:
        src: /tmp/symfony.tar.gz
        dest: /usr/local/bin
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        extra_opts: [--wildcards, symfony]
        remote_src: yes

    - name: Symfony CLI | Check
      command: /usr/local/bin/symfony version
  when: symfony_cli_version not in symfony_cli_installed_version.stdout | default('')

- name: Install auto complete
  shell: |
    mkdir -p ~/.oh-my-zsh/completions
    /usr/local/bin/symfony self:completion zsh > ~/.oh-my-zsh/completions/_symfony
  args:
    creates: ~/.oh-my-zsh/completions/_symfony
