---
- name: Check for existing install
  stat:
    path: ~/AppImages/bitwarden.AppImage
  register: bitwarden_install
  changed_when: False

- block:
    - name: Create AppImages directory
      file:
        path: ~/AppImages/
        state: directory
        mode: 0755

    - name: Install
      get_url:
        url: https://vault.bitwarden.com/download/?app=desktop&platform=linux
        dest: ~/AppImages/bitwarden.AppImage
        mode: 0755
  when: not bitwarden_install.stat.exists

- name: Install logo
  become: true
  copy:
    src: bitwarden.png
    dest: /usr/share/pixmaps/bitwarden.png

- name: Install .desktop
  copy:
    dest: ~/.local/share/applications/bitwarden.desktop
    content: |
      [Desktop Entry]
      Name=Bitwarden
      GenericName=Bitwarden
      Comment=Password manager.
      Exec={{ ansible_env.HOME }}/AppImages/bitwarden.AppImage --no-sandbox
      Icon=bitwarden
      StartupNotify=false
      StartupWMClass=bitwarden
      Terminal=false
      Type=Application
      Categories=Utility;
      Keywords=Bitwarden;Password manager;
  register: bitwarden_desktop_file

- name: Update desktop files
  command: update-desktop-database ~/.local/share/applications -v
  when: bitwarden_desktop_file.changed

# CLI - https://bitwarden.com/help/cli/
- name: Get the latest CLI release
  uri:
    url: "https://api.github.com/repos/bitwarden/clients/releases?per_page=30"
    return_content: yes
  register: bw_releases
  no_log: true

- name: Get CLI version number
  set_fact:
    bw_cli_version: "{{ bw_releases.json | selectattr('tag_name', 'match', '^cli-v') | map(attribute='tag_name') | first | regex_replace('^cli-v', '') }}"

- name: Check installed CLI version
  command: /usr/local/bin/bw --version
  register: bw_cli_installed_version
  changed_when: bw_cli_version != bw_cli_installed_version.stdout | default('') | trim
  failed_when: False

- block:
    - name: Download CLI
      unarchive:
        src: "https://github.com/bitwarden/clients/releases/download/cli-v{{ bw_cli_version }}/bw-linux-{{ bw_cli_version }}.zip"
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
      become: true

    - name: Verify CLI install
      command: /usr/local/bin/bw --version
  when: bw_cli_version != bw_cli_installed_version.stdout | default('') | trim
