---
- name: Clean if force_install is true
  become: true
  file:
    path: /usr/local/bin/zellij
    state: absent
  when: force_install

- name: Install
  shell: |
    (
      cd /tmp
      wget -O zellij.tar.gz "https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz"
      tar -xf zellij.tar.gz zellij
      sudo install zellij /usr/local/bin
      rm zellij.tar.gz zellij
    )
  args:
    creates: /usr/local/bin/zellij
