---
- name: Check for existing installation
  stat:
    path: /home/{{ ansible_user}}/.cargo/bin/grex
  register: grex_install
  changed_when: False

- name: Install
  command: cargo install grex
  when: not grex_install.stat.exists
