---
- name: Install fonts
  shell: |
    set -xe
    
    wget -nv -O "/tmp/{{ item }}.zip" "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip" 
    unzip -o "/tmp/{{ item }}.zip" -d "/tmp/{{ item }}"
    mkdir -p "{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}"
    cp /tmp/{{ item }}/*.ttf "{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}"
    rm -rf "/tmp/{{ item }}" "/tmp/{{ item }}.zip"
  args:
    creates: '{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}'
  with_items:
    - JetBrainsMono
    - Meslo
  register: install_fonts

- name: Install fonts config
  become: true
  copy:
    src: fonts.conf
    dest: /etc/fonts/local.conf

- name: Build fonts information cache files
  shell: fc-cache -rvf
  when: install_fonts.changed
