---
- name: Copy font to src
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/
  with_items:
    - MesloLGS
    - JetBrainsMono
  notify: Build font information cache files

- name: Copy font to src
  become: true
  copy:
    src: fonts.conf
    dest: /etc/fonts/local.conf
  notify: Build font information cache files
