---
- name: Install fonts
  shell: |
    set -x
    
    wget -nv -O "/tmp/{{ item }}.zip" "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip" 
    unzip "/tmp/{{ item }}.zip" -d "/tmp/{{ item }}"
    mkdir -p "~/.local/share/fonts/{{ item }}"
    cp /tmp/{{ item }}/*.ttf "~/.local/share/fonts/{{ item }}"
    rm -rf "/tmp/{{ item }}" "/tmp/{{ item }}.zip"
  with_items:
    - JetBrainsMono
    - Meslo

- name: Install fonts config
  become: true
  copy:
    src: fonts.conf
    dest: /etc/fonts/local.conf

- name: Build fonts information cache files
  shell: fc-cache -rvf
